# Google cloud build instructions
on:
  push:
    branches:
      - master

substitutions:
  SERVICE-NAME: 'bo-raps'
  PROJECT_ID: 'boraps'
  REGION: 'us-central1'

steps:
  # Build the project
  - name: 'Install Angular CLI'
    args: ['npm', 'install', '@angular/cli']
    # Install dependencies
  - name: 'Install dependencies'
    args: ['npm','install']
    # Run project tests
  - name: 'Test application'
    args: ['npm', 'run', 'test-headless']
    # build the container image
  - name: 'Build new application bundle'
    args: ['npm', 'run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$SERVICE-NAME:$COMMIT_SHA', '.']
    # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$SERVICE-NAME:$COMMIT_SHA']
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run','deploy','$SERVICE-NAME','--image','gcr.io/$PROJECT_ID/$SERVICE-NAME:$COMMIT_SHA','--region','$REGION','--platform -managed']

images:
  - 'gcr.io/$PROJECT_ID/$SERVICE-NAME:$COMMIT_SHA'
