FROM ubuntu:18.04
 
    
# wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# apt update

# sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"

# sudo apt-get install -y mssql-serveradd-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"