FROM ubuntu:18.04
 
    
# wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

# apt update

# apt "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"

# apt install -y mssql-serveradd-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list)"

# apt update
# apt install -y mssql-server